remark_args:
  ratio: "16:9"
  slideNumberFormat: "(%current%/%total%)"
  countIncrementalSlides: False
  highlightLines: True
html_template: "{{premark}}/templates/default.html"
stylesheet: "{{premark}}/templates/default.css"
title: Premark Presentation
metafile: sections.yaml
